### ISSUE TITLE
Naming consideration

### ISSUE THREAD

**Issue by mvpmvh** [nicksrandall/dataloader#11]
Obviously this is a personal preference and not at all technical in nature, but how do you feel about renaming your `type Interface interface` to `type DataLoader interface` and `type Loader struct` to `type DefaultDataLoader struct`? I don't have anything concrete to say 1 way or another is best practice or anything like that, but it seems to read more nicely, especially if you're just trying to glance over the godocs of your package to quickly get an understanding of what things are and how they're connected.  Just my $0.02.

**Comment by tonyghita** [comment]
Hmmm... My preference is to take the package name in consideration with the type name.

Consider:
`dataloader.Interface` vs ` dataloader.DataLoader`
`dataloader.Loader` vs `dataloader.DefaultDataLoader`

**Comment by nicksrandall** [comment]
I agree with @tonyghita. `dataloader.Interface` is more clear to me and appears to be a convention used by the Go team. See https://golang.org/pkg/sort/#Interface as an example.
