### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by acornejo** [nicksrandall/dataloader#24]
I got here after reading through the issues in neelance/graphql-go

It is not entirely clear to me how this would solve the n+1 request issue.

I.e. how can you use this to perform less database calls?

**Comment by jagregory** [comment]
It's worth reading the [facebook/dataloader](https://github.com/facebook/dataloader) docs for an overview of what this library is trying to achieve.

In short, within a single HTTP request, every call to `loader.Load` will be batched up into one call to your `batchFn` function.

**Comment by nicksrandall** [comment]
@acornejo did you get the answers you were looking for? Do you mind if I close this issue?
