### ISSUE TITLE
how to load queries without keys 

### ISSUE THREAD

**Issue by johnjerrico** [nicksrandall/dataloader#28]
hello, I've been tinkering with your product by trying to do what the dataloader(facebook JS version) 
```
var UserType = new GraphQLObjectType({
  name: 'User',
  fields: () => ({
    name: { type: GraphQLString },
    bestFriend: {
      type: UserType,
      resolve: user => userLoader.load(user.bestFriendID)
    },
    friends: {
      args: {
        first: { type: GraphQLInt }
      },
      type: new GraphQLList(UserType),
      resolve: (user, { first }) => queryLoader.load([
        'SELECT toID FROM friends WHERE fromID=? LIMIT ?', user.id, first
      ]).then(rows => rows.map(row => userLoader.load(row.toID)))
    }
  })
})
```
is it possible to resolve friends just the way facebook sample does, using your product ? if not what is the alternative  ?

**Comment by nicksrandall** [comment]
Sorry for no response. This implementation attempts to follow the spec as closely as possible. That said, I’m not sure how to answer your question. Any call to a loader will need an identifier (key) of some kind.

**Comment by johnjerrico** [comment]
I'm sorry the reason why I close it, is because I think I am asking the
wrong question

thanks a lot for your kind response

Warm Regards,

JohnJerrico
