### ISSUE TITLE
Running `go test -race` fails

### ISSUE THREAD

**Issue by tonyghita** [nicksrandall/dataloader#3]
Tests fail to pass when specifying the race detector to run.

```sh
go test -v -cover -race
```

results in
```
Found 13 data race(s)
exit status 66
FAIL	github.com/nicksrandall/dataloader	1.059s
```
if the tests don't deadlock.

It may be good to add this option to the TravisCI runner.

**Comment by tonyghita** [comment]
I'm looking at `LoadMany()` for thread-safety... I notice we do some slice manipulation in goroutines and AFAIK slice manipulations are not thread-safe.

**Comment by nicksrandall** [comment]
Thanks for bringing this up. I've just pushed an update that prevents all the race conditions detected.

**Comment by tonyghita** [comment]
Great work! Submitting a PR to add the race detector to TravisCI runs
