### ISSUE TITLE
Return only one error from ThunkMany

### ISSUE THREAD

**Issue by mastertinner** [nicksrandall/dataloader#31]
To me, it's confusing that `BatchFunc` returns `*[]Result`. I would expect it to return `([]interface{}, error)` instead. That would be easier to use and closer to the https://github.com/facebook/dataloader implementation where batch functions can also only throw once and not once per result. If my `BatchFunc` contains a consolidated DB query (which in most cases it will), I can only get one error from that query and would then have to do the following:

```go
results, err := myDBQuery(keys)
if err != nil {
	return []*dataloader.Result{{Error: err}}
}
```

I think that's not nice because it's not sure that the error has something to do with the first result.

The suggestion would result in the following changes:

```diff
-type ThunkMany func() ([]interface{}, []error)
+type ThunkMany func() ([]interface{}, error)

-type BatchFunc func(context.Context, []string) []*Result
+type BatchFunc func(context.Context, []string) ([]interface, error)
```

Currently, I have to do the following for `LoadMany`, which is not nice either:

```go
results, errs := myLoader.LoadMany(ctx, keys)
var err error
for _, e := range errs {
	if e != nil {
		err = e
                break
	}
}
if err != nil {
	// handle data error
}
```

**Comment by tonyghita** [comment]
Hey, the behavior is implemented like this because of this issue: https://github.com/nicksrandall/dataloader/issues/25

It may be nice to return a `nil` value for []error if no errors have occurred instead of a slice of all nil errors.

**Comment by mastertinner** [comment]
Good point. Thanks, @tonyghita! I like your suggestion. What do you think, @nicksrandall?

**Comment by tonyghita** [comment]
I opened #32 to try and address this point. Let me know what you think!

**Comment by mastertinner** [comment]
LGTM! Thanks, @tonyghita!

**Comment by nicksrandall** [comment]
@tonyghita I merged the PR and I also tagged these changes. Thanks for the help!
