### ISSUE TITLE
cannot be batched in graphql

### ISSUE THREAD

**Issue by MingYinLv** [nicksrandall/dataloader#38]
Union query cannot be merged in [graphql](https://github.com/graphql-go/graphql)
```go
var personType = graphql.NewObject(graphql.ObjectConfig{
	Name: "Person",
	Fields: graphql.Fields{
		"id": &graphql.Field{
			Type: graphql.Int,
		},
		"name": &graphql.Field{
			Type: graphql.String,
		},
		"age": &graphql.Field{
			Type: graphql.Int,
		},
		"sex": &graphql.Field{
			Type: graphql.String,
		},
		"friends": &graphql.Field{
			Type: graphql.NewList(friendType),
			Resolve: func(params graphql.ResolveParams) (interface{}, error) {
				idQuery := params.Source.(Person).ID
				i := strconv.Itoa(int(idQuery))
				thunk := friendLoader.Load(context.TODO(), dataloader.StringKey(i))
				return thunk()
			},
		},
	},
})
```

queryString
```
{personList(ids: [1,2]){id,name,age,sex,friends{name}}}
```

After querying multiple Persons, the friends of Person will be queried. Thunk will be called in the Resolve function of friends. batchFn will be called multiple times, each passing an id.

**Comment by tonyghita** [comment]
Executing the `thunk` will block, so the resolver probably is executing in serial rather than in parallel.

You either want to use `LoadMany` with many IDs or `Load` without executing the `thunk`.

**Comment by MingYinLv** [comment]
Thanks, The resolver is executed serially. 
It seems that I need to find a solution to graphql-go.
