### ISSUE TITLE
Thunk return (interface{}, error) in stead of *Result?

### ISSUE THREAD

**Issue by nicksrandall** [nicksrandall/dataloader#6]
I'm thinking about making a small refactor that will change the `Thunk` and `ThunkMany` types to return interface{}, and error (or []interface, []error in the case of ThunkMany). I feel like that would be a little more idiomatic. 

@tonyghita What do you think?

**Comment by tonyghita** [comment]
I like this idea 👍

**Comment by nicksrandall** [comment]
Fixed with #7
